#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FC.Models.Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FC.DB")]
	public partial class FCDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAccount(Account instance);
    partial void UpdateAccount(Account instance);
    partial void DeleteAccount(Account instance);
    partial void InsertFaction(Faction instance);
    partial void UpdateFaction(Faction instance);
    partial void DeleteFaction(Faction instance);
    partial void InsertFleet(Fleet instance);
    partial void UpdateFleet(Fleet instance);
    partial void DeleteFleet(Fleet instance);
    partial void InsertLeaderArchetype(LeaderArchetype instance);
    partial void UpdateLeaderArchetype(LeaderArchetype instance);
    partial void DeleteLeaderArchetype(LeaderArchetype instance);
    partial void InsertLeaderArchetypeSkill(LeaderArchetypeSkill instance);
    partial void UpdateLeaderArchetypeSkill(LeaderArchetypeSkill instance);
    partial void DeleteLeaderArchetypeSkill(LeaderArchetypeSkill instance);
    partial void InsertLeader(Leader instance);
    partial void UpdateLeader(Leader instance);
    partial void DeleteLeader(Leader instance);
    partial void InsertLeaderSkill(LeaderSkill instance);
    partial void UpdateLeaderSkill(LeaderSkill instance);
    partial void DeleteLeaderSkill(LeaderSkill instance);
    partial void InsertModulePrototype(ModulePrototype instance);
    partial void UpdateModulePrototype(ModulePrototype instance);
    partial void DeleteModulePrototype(ModulePrototype instance);
    partial void InsertModule(Module instance);
    partial void UpdateModule(Module instance);
    partial void DeleteModule(Module instance);
    partial void InsertObject(Object instance);
    partial void UpdateObject(Object instance);
    partial void DeleteObject(Object instance);
    partial void InsertObjectType(ObjectType instance);
    partial void UpdateObjectType(ObjectType instance);
    partial void DeleteObjectType(ObjectType instance);
    partial void InsertPlanet(Planet instance);
    partial void UpdatePlanet(Planet instance);
    partial void DeletePlanet(Planet instance);
    partial void InsertShipPrototype(ShipPrototype instance);
    partial void UpdateShipPrototype(ShipPrototype instance);
    partial void DeleteShipPrototype(ShipPrototype instance);
    partial void InsertShip(Ship instance);
    partial void UpdateShip(Ship instance);
    partial void DeleteShip(Ship instance);
    partial void InsertSkill(Skill instance);
    partial void UpdateSkill(Skill instance);
    partial void DeleteSkill(Skill instance);
    partial void InsertStarbase(Starbase instance);
    partial void UpdateStarbase(Starbase instance);
    partial void DeleteStarbase(Starbase instance);
    partial void InsertStar(Star instance);
    partial void UpdateStar(Star instance);
    partial void DeleteStar(Star instance);
    partial void InsertStarSystemArea(StarSystemArea instance);
    partial void UpdateStarSystemArea(StarSystemArea instance);
    partial void DeleteStarSystemArea(StarSystemArea instance);
    partial void InsertCharacter(Character instance);
    partial void UpdateCharacter(Character instance);
    partial void DeleteCharacter(Character instance);
    #endregion
		
		public FCDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["FC_DBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public FCDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FCDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FCDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FCDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Account> Accounts
		{
			get
			{
				return this.GetTable<Account>();
			}
		}
		
		public System.Data.Linq.Table<Faction> Factions
		{
			get
			{
				return this.GetTable<Faction>();
			}
		}
		
		public System.Data.Linq.Table<Fleet> Fleets
		{
			get
			{
				return this.GetTable<Fleet>();
			}
		}
		
		public System.Data.Linq.Table<LeaderArchetype> LeaderArchetypes
		{
			get
			{
				return this.GetTable<LeaderArchetype>();
			}
		}
		
		public System.Data.Linq.Table<LeaderArchetypeSkill> LeaderArchetypeSkills
		{
			get
			{
				return this.GetTable<LeaderArchetypeSkill>();
			}
		}
		
		public System.Data.Linq.Table<Leader> Leaders
		{
			get
			{
				return this.GetTable<Leader>();
			}
		}
		
		public System.Data.Linq.Table<LeaderSkill> LeaderSkills
		{
			get
			{
				return this.GetTable<LeaderSkill>();
			}
		}
		
		public System.Data.Linq.Table<ModulePrototype> ModulePrototypes
		{
			get
			{
				return this.GetTable<ModulePrototype>();
			}
		}
		
		public System.Data.Linq.Table<Module> Modules
		{
			get
			{
				return this.GetTable<Module>();
			}
		}
		
		public System.Data.Linq.Table<Object> Objects
		{
			get
			{
				return this.GetTable<Object>();
			}
		}
		
		public System.Data.Linq.Table<ObjectType> ObjectTypes
		{
			get
			{
				return this.GetTable<ObjectType>();
			}
		}
		
		public System.Data.Linq.Table<Planet> Planets
		{
			get
			{
				return this.GetTable<Planet>();
			}
		}
		
		public System.Data.Linq.Table<ShipPrototype> ShipPrototypes
		{
			get
			{
				return this.GetTable<ShipPrototype>();
			}
		}
		
		public System.Data.Linq.Table<Ship> Ships
		{
			get
			{
				return this.GetTable<Ship>();
			}
		}
		
		public System.Data.Linq.Table<Skill> Skills
		{
			get
			{
				return this.GetTable<Skill>();
			}
		}
		
		public System.Data.Linq.Table<Starbase> Starbases
		{
			get
			{
				return this.GetTable<Starbase>();
			}
		}
		
		public System.Data.Linq.Table<Star> Stars
		{
			get
			{
				return this.GetTable<Star>();
			}
		}
		
		public System.Data.Linq.Table<StarSystemArea> StarSystemAreas
		{
			get
			{
				return this.GetTable<StarSystemArea>();
			}
		}
		
		public System.Data.Linq.Table<Character> Characters
		{
			get
			{
				return this.GetTable<Character>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Accounts")]
	public partial class Account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _Email;
		
		private string _PasswordHash;
		
		private int _Status;
		
		private System.DateTime _CreatedOn;
		
		private System.DateTime _LastLoggedOn;
		
		private string _LastLoginIp;
		
		private int _Type;
		
		private long _Money;
		
		private EntitySet<Character> _Characters;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPasswordHashChanging(string value);
    partial void OnPasswordHashChanged();
    partial void OnStatusChanging(int value);
    partial void OnStatusChanged();
    partial void OnCreatedOnChanging(System.DateTime value);
    partial void OnCreatedOnChanged();
    partial void OnLastLoggedOnChanging(System.DateTime value);
    partial void OnLastLoggedOnChanged();
    partial void OnLastLoginIpChanging(string value);
    partial void OnLastLoginIpChanged();
    partial void OnTypeChanging(int value);
    partial void OnTypeChanged();
    partial void OnMoneyChanging(long value);
    partial void OnMoneyChanged();
    #endregion
		
		public Account()
		{
			this._Characters = new EntitySet<Character>(new Action<Character>(this.attach_Characters), new Action<Character>(this.detach_Characters));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordHash", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string PasswordHash
		{
			get
			{
				return this._PasswordHash;
			}
			set
			{
				if ((this._PasswordHash != value))
				{
					this.OnPasswordHashChanging(value);
					this.SendPropertyChanging();
					this._PasswordHash = value;
					this.SendPropertyChanged("PasswordHash");
					this.OnPasswordHashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int NOT NULL")]
		public int Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLoggedOn", DbType="DateTime NOT NULL")]
		public System.DateTime LastLoggedOn
		{
			get
			{
				return this._LastLoggedOn;
			}
			set
			{
				if ((this._LastLoggedOn != value))
				{
					this.OnLastLoggedOnChanging(value);
					this.SendPropertyChanging();
					this._LastLoggedOn = value;
					this.SendPropertyChanged("LastLoggedOn");
					this.OnLastLoggedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLoginIp", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LastLoginIp
		{
			get
			{
				return this._LastLoginIp;
			}
			set
			{
				if ((this._LastLoginIp != value))
				{
					this.OnLastLoginIpChanging(value);
					this.SendPropertyChanging();
					this._LastLoginIp = value;
					this.SendPropertyChanged("LastLoginIp");
					this.OnLastLoginIpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Int NOT NULL")]
		public int Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Money", DbType="BigInt NOT NULL")]
		public long Money
		{
			get
			{
				return this._Money;
			}
			set
			{
				if ((this._Money != value))
				{
					this.OnMoneyChanging(value);
					this.SendPropertyChanging();
					this._Money = value;
					this.SendPropertyChanged("Money");
					this.OnMoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_Character", Storage="_Characters", ThisKey="Id", OtherKey="AccountId")]
		public EntitySet<Character> Characters
		{
			get
			{
				return this._Characters;
			}
			set
			{
				this._Characters.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Characters(Character entity)
		{
			this.SendPropertyChanging();
			entity.Account = this;
		}
		
		private void detach_Characters(Character entity)
		{
			this.SendPropertyChanging();
			entity.Account = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Factions")]
	public partial class Faction : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _Name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public Faction()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Fleets")]
	public partial class Fleet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private System.Nullable<System.Guid> _FactionId;
		
		private string _Name;
		
		private System.Nullable<System.Guid> _AccountId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnFactionIdChanging(System.Nullable<System.Guid> value);
    partial void OnFactionIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnAccountIdChanging(System.Nullable<System.Guid> value);
    partial void OnAccountIdChanged();
    #endregion
		
		public Fleet()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FactionId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> FactionId
		{
			get
			{
				return this._FactionId;
			}
			set
			{
				if ((this._FactionId != value))
				{
					this.OnFactionIdChanging(value);
					this.SendPropertyChanging();
					this._FactionId = value;
					this.SendPropertyChanged("FactionId");
					this.OnFactionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> AccountId
		{
			get
			{
				return this._AccountId;
			}
			set
			{
				if ((this._AccountId != value))
				{
					this.OnAccountIdChanging(value);
					this.SendPropertyChanging();
					this._AccountId = value;
					this.SendPropertyChanged("AccountId");
					this.OnAccountIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LeaderArchetypes")]
	public partial class LeaderArchetype : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _Name;
		
		private int _BaseIntelligence;
		
		private int _BaseCharisma;
		
		private int _BaseWillpower;
		
		private string _Bonuses;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnBaseIntelligenceChanging(int value);
    partial void OnBaseIntelligenceChanged();
    partial void OnBaseCharismaChanging(int value);
    partial void OnBaseCharismaChanged();
    partial void OnBaseWillpowerChanging(int value);
    partial void OnBaseWillpowerChanged();
    partial void OnBonusesChanging(string value);
    partial void OnBonusesChanged();
    #endregion
		
		public LeaderArchetype()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseIntelligence", DbType="Int NOT NULL")]
		public int BaseIntelligence
		{
			get
			{
				return this._BaseIntelligence;
			}
			set
			{
				if ((this._BaseIntelligence != value))
				{
					this.OnBaseIntelligenceChanging(value);
					this.SendPropertyChanging();
					this._BaseIntelligence = value;
					this.SendPropertyChanged("BaseIntelligence");
					this.OnBaseIntelligenceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseCharisma", DbType="Int NOT NULL")]
		public int BaseCharisma
		{
			get
			{
				return this._BaseCharisma;
			}
			set
			{
				if ((this._BaseCharisma != value))
				{
					this.OnBaseCharismaChanging(value);
					this.SendPropertyChanging();
					this._BaseCharisma = value;
					this.SendPropertyChanged("BaseCharisma");
					this.OnBaseCharismaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseWillpower", DbType="Int NOT NULL")]
		public int BaseWillpower
		{
			get
			{
				return this._BaseWillpower;
			}
			set
			{
				if ((this._BaseWillpower != value))
				{
					this.OnBaseWillpowerChanging(value);
					this.SendPropertyChanging();
					this._BaseWillpower = value;
					this.SendPropertyChanged("BaseWillpower");
					this.OnBaseWillpowerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bonuses", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Bonuses
		{
			get
			{
				return this._Bonuses;
			}
			set
			{
				if ((this._Bonuses != value))
				{
					this.OnBonusesChanging(value);
					this.SendPropertyChanging();
					this._Bonuses = value;
					this.SendPropertyChanged("Bonuses");
					this.OnBonusesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LeaderArchetypeSkills")]
	public partial class LeaderArchetypeSkill : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private System.Guid _LeaderArchetypeId;
		
		private System.Guid _SkillId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnLeaderArchetypeIdChanging(System.Guid value);
    partial void OnLeaderArchetypeIdChanged();
    partial void OnSkillIdChanging(System.Guid value);
    partial void OnSkillIdChanged();
    #endregion
		
		public LeaderArchetypeSkill()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeaderArchetypeId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid LeaderArchetypeId
		{
			get
			{
				return this._LeaderArchetypeId;
			}
			set
			{
				if ((this._LeaderArchetypeId != value))
				{
					this.OnLeaderArchetypeIdChanging(value);
					this.SendPropertyChanging();
					this._LeaderArchetypeId = value;
					this.SendPropertyChanged("LeaderArchetypeId");
					this.OnLeaderArchetypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SkillId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid SkillId
		{
			get
			{
				return this._SkillId;
			}
			set
			{
				if ((this._SkillId != value))
				{
					this.OnSkillIdChanging(value);
					this.SendPropertyChanging();
					this._SkillId = value;
					this.SendPropertyChanged("SkillId");
					this.OnSkillIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Leaders")]
	public partial class Leader : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _Name;
		
		private string _Description;
		
		private int _Intelligence;
		
		private int _Charisma;
		
		private int _Willpower;
		
		private System.Nullable<System.Guid> _ImplantId;
		
		private string _Bonuses;
		
		private int _ShipSlotNumber;
		
		private System.Nullable<System.Guid> _ShipId;
		
		private System.Nullable<System.Guid> _StationId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnIntelligenceChanging(int value);
    partial void OnIntelligenceChanged();
    partial void OnCharismaChanging(int value);
    partial void OnCharismaChanged();
    partial void OnWillpowerChanging(int value);
    partial void OnWillpowerChanged();
    partial void OnImplantIdChanging(System.Nullable<System.Guid> value);
    partial void OnImplantIdChanged();
    partial void OnBonusesChanging(string value);
    partial void OnBonusesChanged();
    partial void OnShipSlotNumberChanging(int value);
    partial void OnShipSlotNumberChanged();
    partial void OnShipIdChanging(System.Nullable<System.Guid> value);
    partial void OnShipIdChanged();
    partial void OnStationIdChanging(System.Nullable<System.Guid> value);
    partial void OnStationIdChanged();
    #endregion
		
		public Leader()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Intelligence", DbType="Int NOT NULL")]
		public int Intelligence
		{
			get
			{
				return this._Intelligence;
			}
			set
			{
				if ((this._Intelligence != value))
				{
					this.OnIntelligenceChanging(value);
					this.SendPropertyChanging();
					this._Intelligence = value;
					this.SendPropertyChanged("Intelligence");
					this.OnIntelligenceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Charisma", DbType="Int NOT NULL")]
		public int Charisma
		{
			get
			{
				return this._Charisma;
			}
			set
			{
				if ((this._Charisma != value))
				{
					this.OnCharismaChanging(value);
					this.SendPropertyChanging();
					this._Charisma = value;
					this.SendPropertyChanged("Charisma");
					this.OnCharismaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Willpower", DbType="Int NOT NULL")]
		public int Willpower
		{
			get
			{
				return this._Willpower;
			}
			set
			{
				if ((this._Willpower != value))
				{
					this.OnWillpowerChanging(value);
					this.SendPropertyChanging();
					this._Willpower = value;
					this.SendPropertyChanged("Willpower");
					this.OnWillpowerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImplantId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ImplantId
		{
			get
			{
				return this._ImplantId;
			}
			set
			{
				if ((this._ImplantId != value))
				{
					this.OnImplantIdChanging(value);
					this.SendPropertyChanging();
					this._ImplantId = value;
					this.SendPropertyChanged("ImplantId");
					this.OnImplantIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bonuses", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Bonuses
		{
			get
			{
				return this._Bonuses;
			}
			set
			{
				if ((this._Bonuses != value))
				{
					this.OnBonusesChanging(value);
					this.SendPropertyChanging();
					this._Bonuses = value;
					this.SendPropertyChanged("Bonuses");
					this.OnBonusesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipSlotNumber", DbType="Int NOT NULL")]
		public int ShipSlotNumber
		{
			get
			{
				return this._ShipSlotNumber;
			}
			set
			{
				if ((this._ShipSlotNumber != value))
				{
					this.OnShipSlotNumberChanging(value);
					this.SendPropertyChanging();
					this._ShipSlotNumber = value;
					this.SendPropertyChanged("ShipSlotNumber");
					this.OnShipSlotNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ShipId
		{
			get
			{
				return this._ShipId;
			}
			set
			{
				if ((this._ShipId != value))
				{
					this.OnShipIdChanging(value);
					this.SendPropertyChanging();
					this._ShipId = value;
					this.SendPropertyChanged("ShipId");
					this.OnShipIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StationId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> StationId
		{
			get
			{
				return this._StationId;
			}
			set
			{
				if ((this._StationId != value))
				{
					this.OnStationIdChanging(value);
					this.SendPropertyChanging();
					this._StationId = value;
					this.SendPropertyChanged("StationId");
					this.OnStationIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LeaderSkills")]
	public partial class LeaderSkill : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private System.Guid _LeaderId;
		
		private System.Guid _SkillId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnLeaderIdChanging(System.Guid value);
    partial void OnLeaderIdChanged();
    partial void OnSkillIdChanging(System.Guid value);
    partial void OnSkillIdChanged();
    #endregion
		
		public LeaderSkill()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeaderId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid LeaderId
		{
			get
			{
				return this._LeaderId;
			}
			set
			{
				if ((this._LeaderId != value))
				{
					this.OnLeaderIdChanging(value);
					this.SendPropertyChanging();
					this._LeaderId = value;
					this.SendPropertyChanged("LeaderId");
					this.OnLeaderIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SkillId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid SkillId
		{
			get
			{
				return this._SkillId;
			}
			set
			{
				if ((this._SkillId != value))
				{
					this.OnSkillIdChanging(value);
					this.SendPropertyChanging();
					this._SkillId = value;
					this.SendPropertyChanged("SkillId");
					this.OnSkillIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ModulePrototypes")]
	public partial class ModulePrototype : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _Name;
		
		private string _Description;
		
		private string _Effects;
		
		private string _Requirements;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnEffectsChanging(string value);
    partial void OnEffectsChanged();
    partial void OnRequirementsChanging(string value);
    partial void OnRequirementsChanged();
    #endregion
		
		public ModulePrototype()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Effects", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Effects
		{
			get
			{
				return this._Effects;
			}
			set
			{
				if ((this._Effects != value))
				{
					this.OnEffectsChanging(value);
					this.SendPropertyChanging();
					this._Effects = value;
					this.SendPropertyChanged("Effects");
					this.OnEffectsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Requirements", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Requirements
		{
			get
			{
				return this._Requirements;
			}
			set
			{
				if ((this._Requirements != value))
				{
					this.OnRequirementsChanging(value);
					this.SendPropertyChanging();
					this._Requirements = value;
					this.SendPropertyChanged("Requirements");
					this.OnRequirementsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Modules")]
	public partial class Module : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private System.Guid _ModuleType;
		
		private System.Nullable<System.Guid> _ShipId;
		
		private int _ShipSlotNumber;
		
		private System.Nullable<System.Guid> _StationId;
		
		private int _Condition;
		
		private System.Nullable<System.Guid> _AccountId;
		
		private int _State;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnModuleTypeChanging(System.Guid value);
    partial void OnModuleTypeChanged();
    partial void OnShipIdChanging(System.Nullable<System.Guid> value);
    partial void OnShipIdChanged();
    partial void OnShipSlotNumberChanging(int value);
    partial void OnShipSlotNumberChanged();
    partial void OnStationIdChanging(System.Nullable<System.Guid> value);
    partial void OnStationIdChanged();
    partial void OnConditionChanging(int value);
    partial void OnConditionChanged();
    partial void OnAccountIdChanging(System.Nullable<System.Guid> value);
    partial void OnAccountIdChanged();
    partial void OnStateChanging(int value);
    partial void OnStateChanged();
    #endregion
		
		public Module()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModuleType", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ModuleType
		{
			get
			{
				return this._ModuleType;
			}
			set
			{
				if ((this._ModuleType != value))
				{
					this.OnModuleTypeChanging(value);
					this.SendPropertyChanging();
					this._ModuleType = value;
					this.SendPropertyChanged("ModuleType");
					this.OnModuleTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ShipId
		{
			get
			{
				return this._ShipId;
			}
			set
			{
				if ((this._ShipId != value))
				{
					this.OnShipIdChanging(value);
					this.SendPropertyChanging();
					this._ShipId = value;
					this.SendPropertyChanged("ShipId");
					this.OnShipIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipSlotNumber", DbType="Int NOT NULL")]
		public int ShipSlotNumber
		{
			get
			{
				return this._ShipSlotNumber;
			}
			set
			{
				if ((this._ShipSlotNumber != value))
				{
					this.OnShipSlotNumberChanging(value);
					this.SendPropertyChanging();
					this._ShipSlotNumber = value;
					this.SendPropertyChanged("ShipSlotNumber");
					this.OnShipSlotNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StationId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> StationId
		{
			get
			{
				return this._StationId;
			}
			set
			{
				if ((this._StationId != value))
				{
					this.OnStationIdChanging(value);
					this.SendPropertyChanging();
					this._StationId = value;
					this.SendPropertyChanged("StationId");
					this.OnStationIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Condition", DbType="Int NOT NULL")]
		public int Condition
		{
			get
			{
				return this._Condition;
			}
			set
			{
				if ((this._Condition != value))
				{
					this.OnConditionChanging(value);
					this.SendPropertyChanging();
					this._Condition = value;
					this.SendPropertyChanged("Condition");
					this.OnConditionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> AccountId
		{
			get
			{
				return this._AccountId;
			}
			set
			{
				if ((this._AccountId != value))
				{
					this.OnAccountIdChanging(value);
					this.SendPropertyChanging();
					this._AccountId = value;
					this.SendPropertyChanged("AccountId");
					this.OnAccountIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="Int NOT NULL")]
		public int State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Objects")]
	public partial class Object : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    #endregion
		
		public Object()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ObjectTypes")]
	public partial class ObjectType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private System.Nullable<int> _Money;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnMoneyChanging(System.Nullable<int> value);
    partial void OnMoneyChanged();
    #endregion
		
		public ObjectType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Money", DbType="Int")]
		public System.Nullable<int> Money
		{
			get
			{
				return this._Money;
			}
			set
			{
				if ((this._Money != value))
				{
					this.OnMoneyChanging(value);
					this.SendPropertyChanging();
					this._Money = value;
					this.SendPropertyChanged("Money");
					this.OnMoneyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Planets")]
	public partial class Planet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _Name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public Planet()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ShipPrototypes")]
	public partial class ShipPrototype : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _Name;
		
		private int _Type;
		
		private int _BaseArmor;
		
		private int _BaseShield;
		
		private int _BaseEnergy;
		
		private int _GunSlots;
		
		private int _UtilitySlots;
		
		private int _ComanderSlots;
		
		private string _ComanderRequirements;
		
		private string _Resistances;
		
		private string _Description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnTypeChanging(int value);
    partial void OnTypeChanged();
    partial void OnBaseArmorChanging(int value);
    partial void OnBaseArmorChanged();
    partial void OnBaseShieldChanging(int value);
    partial void OnBaseShieldChanged();
    partial void OnBaseEnergyChanging(int value);
    partial void OnBaseEnergyChanged();
    partial void OnGunSlotsChanging(int value);
    partial void OnGunSlotsChanged();
    partial void OnUtilitySlotsChanging(int value);
    partial void OnUtilitySlotsChanged();
    partial void OnComanderSlotsChanging(int value);
    partial void OnComanderSlotsChanged();
    partial void OnComanderRequirementsChanging(string value);
    partial void OnComanderRequirementsChanged();
    partial void OnResistancesChanging(string value);
    partial void OnResistancesChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public ShipPrototype()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Int NOT NULL")]
		public int Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseArmor", DbType="Int NOT NULL")]
		public int BaseArmor
		{
			get
			{
				return this._BaseArmor;
			}
			set
			{
				if ((this._BaseArmor != value))
				{
					this.OnBaseArmorChanging(value);
					this.SendPropertyChanging();
					this._BaseArmor = value;
					this.SendPropertyChanged("BaseArmor");
					this.OnBaseArmorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseShield", DbType="Int NOT NULL")]
		public int BaseShield
		{
			get
			{
				return this._BaseShield;
			}
			set
			{
				if ((this._BaseShield != value))
				{
					this.OnBaseShieldChanging(value);
					this.SendPropertyChanging();
					this._BaseShield = value;
					this.SendPropertyChanged("BaseShield");
					this.OnBaseShieldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseEnergy", DbType="Int NOT NULL")]
		public int BaseEnergy
		{
			get
			{
				return this._BaseEnergy;
			}
			set
			{
				if ((this._BaseEnergy != value))
				{
					this.OnBaseEnergyChanging(value);
					this.SendPropertyChanging();
					this._BaseEnergy = value;
					this.SendPropertyChanged("BaseEnergy");
					this.OnBaseEnergyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GunSlots", DbType="Int NOT NULL")]
		public int GunSlots
		{
			get
			{
				return this._GunSlots;
			}
			set
			{
				if ((this._GunSlots != value))
				{
					this.OnGunSlotsChanging(value);
					this.SendPropertyChanging();
					this._GunSlots = value;
					this.SendPropertyChanged("GunSlots");
					this.OnGunSlotsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UtilitySlots", DbType="Int NOT NULL")]
		public int UtilitySlots
		{
			get
			{
				return this._UtilitySlots;
			}
			set
			{
				if ((this._UtilitySlots != value))
				{
					this.OnUtilitySlotsChanging(value);
					this.SendPropertyChanging();
					this._UtilitySlots = value;
					this.SendPropertyChanged("UtilitySlots");
					this.OnUtilitySlotsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComanderSlots", DbType="Int NOT NULL")]
		public int ComanderSlots
		{
			get
			{
				return this._ComanderSlots;
			}
			set
			{
				if ((this._ComanderSlots != value))
				{
					this.OnComanderSlotsChanging(value);
					this.SendPropertyChanging();
					this._ComanderSlots = value;
					this.SendPropertyChanged("ComanderSlots");
					this.OnComanderSlotsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComanderRequirements", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string ComanderRequirements
		{
			get
			{
				return this._ComanderRequirements;
			}
			set
			{
				if ((this._ComanderRequirements != value))
				{
					this.OnComanderRequirementsChanging(value);
					this.SendPropertyChanging();
					this._ComanderRequirements = value;
					this.SendPropertyChanged("ComanderRequirements");
					this.OnComanderRequirementsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resistances", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Resistances
		{
			get
			{
				return this._Resistances;
			}
			set
			{
				if ((this._Resistances != value))
				{
					this.OnResistancesChanging(value);
					this.SendPropertyChanging();
					this._Resistances = value;
					this.SendPropertyChanged("Resistances");
					this.OnResistancesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ships")]
	public partial class Ship : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private System.Guid _FleetId;
		
		private string _Name;
		
		private System.Guid _ShipType;
		
		private int _CurrentArmor;
		
		private int _CurrentShield;
		
		private int _CurrentEnergy;
		
		private string _CurrentResistances;
		
		private string _AttackValues;
		
		private int _LocationX;
		
		private int _LocationY;
		
		private int _MaxArmor;
		
		private int _MaxShield;
		
		private int _MaxEnergy;
		
		private string _Effects;
		
		private System.Guid _StationId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnFleetIdChanging(System.Guid value);
    partial void OnFleetIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnShipTypeChanging(System.Guid value);
    partial void OnShipTypeChanged();
    partial void OnCurrentArmorChanging(int value);
    partial void OnCurrentArmorChanged();
    partial void OnCurrentShieldChanging(int value);
    partial void OnCurrentShieldChanged();
    partial void OnCurrentEnergyChanging(int value);
    partial void OnCurrentEnergyChanged();
    partial void OnCurrentResistancesChanging(string value);
    partial void OnCurrentResistancesChanged();
    partial void OnAttackValuesChanging(string value);
    partial void OnAttackValuesChanged();
    partial void OnLocationXChanging(int value);
    partial void OnLocationXChanged();
    partial void OnLocationYChanging(int value);
    partial void OnLocationYChanged();
    partial void OnMaxArmorChanging(int value);
    partial void OnMaxArmorChanged();
    partial void OnMaxShieldChanging(int value);
    partial void OnMaxShieldChanged();
    partial void OnMaxEnergyChanging(int value);
    partial void OnMaxEnergyChanged();
    partial void OnEffectsChanging(string value);
    partial void OnEffectsChanged();
    partial void OnStationIdChanging(System.Guid value);
    partial void OnStationIdChanged();
    #endregion
		
		public Ship()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FleetId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid FleetId
		{
			get
			{
				return this._FleetId;
			}
			set
			{
				if ((this._FleetId != value))
				{
					this.OnFleetIdChanging(value);
					this.SendPropertyChanging();
					this._FleetId = value;
					this.SendPropertyChanged("FleetId");
					this.OnFleetIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipType", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ShipType
		{
			get
			{
				return this._ShipType;
			}
			set
			{
				if ((this._ShipType != value))
				{
					this.OnShipTypeChanging(value);
					this.SendPropertyChanging();
					this._ShipType = value;
					this.SendPropertyChanged("ShipType");
					this.OnShipTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentArmor", DbType="Int NOT NULL")]
		public int CurrentArmor
		{
			get
			{
				return this._CurrentArmor;
			}
			set
			{
				if ((this._CurrentArmor != value))
				{
					this.OnCurrentArmorChanging(value);
					this.SendPropertyChanging();
					this._CurrentArmor = value;
					this.SendPropertyChanged("CurrentArmor");
					this.OnCurrentArmorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentShield", DbType="Int NOT NULL")]
		public int CurrentShield
		{
			get
			{
				return this._CurrentShield;
			}
			set
			{
				if ((this._CurrentShield != value))
				{
					this.OnCurrentShieldChanging(value);
					this.SendPropertyChanging();
					this._CurrentShield = value;
					this.SendPropertyChanged("CurrentShield");
					this.OnCurrentShieldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentEnergy", DbType="Int NOT NULL")]
		public int CurrentEnergy
		{
			get
			{
				return this._CurrentEnergy;
			}
			set
			{
				if ((this._CurrentEnergy != value))
				{
					this.OnCurrentEnergyChanging(value);
					this.SendPropertyChanging();
					this._CurrentEnergy = value;
					this.SendPropertyChanged("CurrentEnergy");
					this.OnCurrentEnergyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentResistances", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string CurrentResistances
		{
			get
			{
				return this._CurrentResistances;
			}
			set
			{
				if ((this._CurrentResistances != value))
				{
					this.OnCurrentResistancesChanging(value);
					this.SendPropertyChanging();
					this._CurrentResistances = value;
					this.SendPropertyChanged("CurrentResistances");
					this.OnCurrentResistancesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttackValues", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string AttackValues
		{
			get
			{
				return this._AttackValues;
			}
			set
			{
				if ((this._AttackValues != value))
				{
					this.OnAttackValuesChanging(value);
					this.SendPropertyChanging();
					this._AttackValues = value;
					this.SendPropertyChanged("AttackValues");
					this.OnAttackValuesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationX", DbType="Int NOT NULL")]
		public int LocationX
		{
			get
			{
				return this._LocationX;
			}
			set
			{
				if ((this._LocationX != value))
				{
					this.OnLocationXChanging(value);
					this.SendPropertyChanging();
					this._LocationX = value;
					this.SendPropertyChanged("LocationX");
					this.OnLocationXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationY", DbType="Int NOT NULL")]
		public int LocationY
		{
			get
			{
				return this._LocationY;
			}
			set
			{
				if ((this._LocationY != value))
				{
					this.OnLocationYChanging(value);
					this.SendPropertyChanging();
					this._LocationY = value;
					this.SendPropertyChanged("LocationY");
					this.OnLocationYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxArmor", DbType="Int NOT NULL")]
		public int MaxArmor
		{
			get
			{
				return this._MaxArmor;
			}
			set
			{
				if ((this._MaxArmor != value))
				{
					this.OnMaxArmorChanging(value);
					this.SendPropertyChanging();
					this._MaxArmor = value;
					this.SendPropertyChanged("MaxArmor");
					this.OnMaxArmorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxShield", DbType="Int NOT NULL")]
		public int MaxShield
		{
			get
			{
				return this._MaxShield;
			}
			set
			{
				if ((this._MaxShield != value))
				{
					this.OnMaxShieldChanging(value);
					this.SendPropertyChanging();
					this._MaxShield = value;
					this.SendPropertyChanged("MaxShield");
					this.OnMaxShieldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxEnergy", DbType="Int NOT NULL")]
		public int MaxEnergy
		{
			get
			{
				return this._MaxEnergy;
			}
			set
			{
				if ((this._MaxEnergy != value))
				{
					this.OnMaxEnergyChanging(value);
					this.SendPropertyChanging();
					this._MaxEnergy = value;
					this.SendPropertyChanged("MaxEnergy");
					this.OnMaxEnergyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Effects", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Effects
		{
			get
			{
				return this._Effects;
			}
			set
			{
				if ((this._Effects != value))
				{
					this.OnEffectsChanging(value);
					this.SendPropertyChanging();
					this._Effects = value;
					this.SendPropertyChanged("Effects");
					this.OnEffectsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StationId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid StationId
		{
			get
			{
				return this._StationId;
			}
			set
			{
				if ((this._StationId != value))
				{
					this.OnStationIdChanging(value);
					this.SendPropertyChanging();
					this._StationId = value;
					this.SendPropertyChanged("StationId");
					this.OnStationIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Skills")]
	public partial class Skill : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _Name;
		
		private string _Description;
		
		private string _EffectCode;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnEffectCodeChanging(string value);
    partial void OnEffectCodeChanged();
    #endregion
		
		public Skill()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EffectCode", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string EffectCode
		{
			get
			{
				return this._EffectCode;
			}
			set
			{
				if ((this._EffectCode != value))
				{
					this.OnEffectCodeChanging(value);
					this.SendPropertyChanging();
					this._EffectCode = value;
					this.SendPropertyChanged("EffectCode");
					this.OnEffectCodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Starbases")]
	public partial class Starbase : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    #endregion
		
		public Starbase()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Stars")]
	public partial class Star : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _Name;
		
		private int _Class;
		
		private int _Status;
		
		private double _LocationX;
		
		private double _LocationY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnClassChanging(int value);
    partial void OnClassChanged();
    partial void OnStatusChanging(int value);
    partial void OnStatusChanged();
    partial void OnLocationXChanging(double value);
    partial void OnLocationXChanged();
    partial void OnLocationYChanging(double value);
    partial void OnLocationYChanged();
    #endregion
		
		public Star()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Class", DbType="Int NOT NULL")]
		public int Class
		{
			get
			{
				return this._Class;
			}
			set
			{
				if ((this._Class != value))
				{
					this.OnClassChanging(value);
					this.SendPropertyChanging();
					this._Class = value;
					this.SendPropertyChanged("Class");
					this.OnClassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int NOT NULL")]
		public int Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationX", DbType="Float NOT NULL")]
		public double LocationX
		{
			get
			{
				return this._LocationX;
			}
			set
			{
				if ((this._LocationX != value))
				{
					this.OnLocationXChanging(value);
					this.SendPropertyChanging();
					this._LocationX = value;
					this.SendPropertyChanged("LocationX");
					this.OnLocationXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationY", DbType="Float NOT NULL")]
		public double LocationY
		{
			get
			{
				return this._LocationY;
			}
			set
			{
				if ((this._LocationY != value))
				{
					this.OnLocationYChanging(value);
					this.SendPropertyChanging();
					this._LocationY = value;
					this.SendPropertyChanged("LocationY");
					this.OnLocationYChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StarSystemAreas")]
	public partial class StarSystemArea : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private System.Guid _PlanetId;
		
		private string _Name;
		
		private int _Type;
		
		private int _Number;
		
		private System.Guid _DropTableId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnPlanetIdChanging(System.Guid value);
    partial void OnPlanetIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnTypeChanging(int value);
    partial void OnTypeChanged();
    partial void OnNumberChanging(int value);
    partial void OnNumberChanged();
    partial void OnDropTableIdChanging(System.Guid value);
    partial void OnDropTableIdChanged();
    #endregion
		
		public StarSystemArea()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlanetId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid PlanetId
		{
			get
			{
				return this._PlanetId;
			}
			set
			{
				if ((this._PlanetId != value))
				{
					this.OnPlanetIdChanging(value);
					this.SendPropertyChanging();
					this._PlanetId = value;
					this.SendPropertyChanged("PlanetId");
					this.OnPlanetIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Int NOT NULL")]
		public int Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number", DbType="Int NOT NULL")]
		public int Number
		{
			get
			{
				return this._Number;
			}
			set
			{
				if ((this._Number != value))
				{
					this.OnNumberChanging(value);
					this.SendPropertyChanging();
					this._Number = value;
					this.SendPropertyChanged("Number");
					this.OnNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DropTableId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid DropTableId
		{
			get
			{
				return this._DropTableId;
			}
			set
			{
				if ((this._DropTableId != value))
				{
					this.OnDropTableIdChanging(value);
					this.SendPropertyChanging();
					this._DropTableId = value;
					this.SendPropertyChanged("DropTableId");
					this.OnDropTableIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Characters")]
	public partial class Character : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private System.Guid _AccountId;
		
		private string _Name;
		
		private EntityRef<Account> _Account;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnAccountIdChanging(System.Guid value);
    partial void OnAccountIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public Character()
		{
			this._Account = default(EntityRef<Account>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid AccountId
		{
			get
			{
				return this._AccountId;
			}
			set
			{
				if ((this._AccountId != value))
				{
					if (this._Account.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAccountIdChanging(value);
					this.SendPropertyChanging();
					this._AccountId = value;
					this.SendPropertyChanged("AccountId");
					this.OnAccountIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_Character", Storage="_Account", ThisKey="AccountId", OtherKey="Id", IsForeignKey=true)]
		public Account Account
		{
			get
			{
				return this._Account.Entity;
			}
			set
			{
				Account previousValue = this._Account.Entity;
				if (((previousValue != value) 
							|| (this._Account.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Account.Entity = null;
						previousValue.Characters.Remove(this);
					}
					this._Account.Entity = value;
					if ((value != null))
					{
						value.Characters.Add(this);
						this._AccountId = value.Id;
					}
					else
					{
						this._AccountId = default(System.Guid);
					}
					this.SendPropertyChanged("Account");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
